DOCUMENT.QUERYSELECTOR( '.HEADER__MOON').ONCLICK= FUNCTION() {
	DOCUMENT.QUERYSELECTOR('BODY').CLASSLIST.TOOGLE('IS-BLACK');
}

DOCUMENT.QUERYSELECTOR(',HEADER__MOB-MENU').ONCLICK= FUNCTION() {
 BDOCUMENT.QUERYSELECTOR(',').CLASSLIST.TOOGLE('IS-BLACK');
}